[datastore_config]
type = "GCS"

[datastore_config.params]
destination_bucket_path = "sdf-ledger-close-meta/v1/ledgers/pubnet"

[datastore_config.schema]
ledgers_per_file = 1
files_per_partition = 64000

[stellar_core_config]
  network = "pubnet"

[postgres_config]
  host = "34.122.97.123"
  user = "postgres"
  database = "postgres"
  port = 5432
