name: Build Dev Image

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected == 'true' && github.sha || github.ref }}-{{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-and-push-container-image:
    name: Build and push a sha tagged container image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Add SHORT_SHA env property with commit short sha
        run: |
          SHORT_SHA=$(git rev-parse --short=9 HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "Short SHA: $SHORT_SHA"

      - name: Set image tag based on branch
        run: |
          IMAGE_TAG="stellar/stellar-ledger-data-indexer:${SHORT_SHA}-dev"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "Image tag: $IMAGE_TAG"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image
        run: make docker-build
        env:
          INDEXERHASH: ${{ env.IMAGE_TAG }}
      - name: Push image to DockerHub
        run: make docker-push
        env:
          INDEXERHASH: ${{ env.IMAGE_TAG }}
